Contribution guide
naps-dev/suricata pull request #21
Opened 2023-06-27 13:55 UTC by Vandiver247

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

For example:

Currently, the software does X, but this PR will allow it to do Y.

Currently, the software does not do X, but this PR will allow it to do X.

Currently, the software does X when specific thing happens causing bad things to happens, but this PR will fix it to do Y without the bad things.

New dependencies added:
- dependency 1 for reason
- dependency 2 for reason

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration - Change as necessary**:
* Kubernetes version:
* Hardware:
* Capability:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added a plain language explanation of the changes to the Unreleased section of the CHANGELOG.md file

2023-06-27 14:08 UTC, benmountjoy111 commented on README.md
> +5. In the dco-core repository, navigate open the file `.github/workflows/suricata.yaml` and update `REF_NAME` variable to match the branch name you created in the suricata repository. Also update the
navigate *to* and open the file

2023-06-27 14:11 UTC, benmountjoy111 commented on README.md
> +`v7.0.0-4`
i thought we were one-based index? i dont have a strong opinion either way, but i thought the first tag would be 'v7.0.0-1' and the fifth would be 'v7.0.0-5'

2023-06-27 14:14 UTC, Vandiver247 commented on README.md
> +`v7.0.0-4`
I think it's currently tagged as 7.0.0-0. I thought we were using a zero based. If not, that's not a problem, I can correct it, we should confirm with the team.

2023-06-27 14:50 UTC, jamesallen-atx approved these changes

2023-06-28 14:33 UTC, Vandiver247 commented on README.md
> +5. In the dco-core repository, navigate open the file `.github/workflows/suricata.yaml` and update `REF_NAME` variable to match the branch name you created in the suricata repository. Also update the
fixed

2023-06-28 17:43 UTC, Vandiver247 commented on README.md
> +`v7.0.0-4`
Updated

2023-06-29 16:01 UTC, timblaktu requested changes

2023-06-29 16:22 UTC, Vandiver247 commented on README.md
> +8. In the list of actions, look for an action titled `<your_github_username> is building the Suricata package`. Wait for this action to complete.
Updated

2023-06-29 18:38 UTC, Vandiver247 reviewed
Approved

2023-06-29 19:23 UTC, timblaktu commented
@Vandiver247 I think there's a problem in the guide WRT properly handling changes made in 2 repos. We guide the user to only submit one PR, in dco-core (to merge the changes made to the issue branch in dco-core to point to a new suricata branch so it can test the change. As it is now, at the end of the process, `dco-core` has been merged to main, but the workflows still point to the suricata issue branch.

I may have just misinterpreted your intent in what the "final PR" is, but either way, it needs to be fixed to clarify which repo the PR is in, and finally to remove the dco-core issue branch, which is vestigial at this point.

2023-06-29 19:34 UTC, timblaktu commented
@Vandiver247 I just pushed a commit that resolves my last comment. I'll approve the PR, but let me know if you find anything wrong with my logic there..

2023-06-29 19:35 UTC, timblaktu approved these changes

2023-06-29 20:24 UTC, timblaktu commented
@Vandiver247 I pushed the final update as we discussed. @jamesallen-atx @benmountjoy111 any chance one of you could review/approve? My approval no longer counts since I contributed commits...

2023-06-29 22:30 UTC, timblaktu commented
Per @docandrew's request I added a minor change to contrib-guide to make it more explicit that we're using a 1-based suffix in the version and what it means.

2023-06-30 13:29 UTC, docandrew approved these changes
This is a very welcome addition!

2023-06-30 14:17 UTC, benmountjoy111 approved these changes
Looks solid. Excellent work!

2023-06-30 16:58 UTC, laurenmengert commented on README.md
> +1. Create a new branch, named to clearly reflect the issue it corresponds to.
Would update to "Create a new branch named to reflect the corresponding issue."

2023-06-30 16:58 UTC, laurenmengert commented on README.md
> +    * This is trivial using the [Development side bar on the issue page](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue).
This is a weird sentence to me. Are we trying to get across how easy it is to create a branch?

2023-06-30 16:59 UTC, laurenmengert commented on README.md
> +    * `REF_NAME` variable matches the name of issue branch created earlier.
Maybe be more specific "variable matches the name of the issue branch created earlier in the Suricata repo"

2023-06-30 19:40 UTC, timblaktu commented on README.md
> +    * This is trivial using the [Development side bar on the issue page](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue).
Mmm sort of, @laurenmengert. Point here is not to shame people into creating a dedicated branch, but to promote the best practice of letting GitHub automate the branch naming for us, using the feature mentioned here. I've found that many people aren't aware of the Development side-bar, which is I think still a beta feature. In this light, is there another way you think this should be worded?

2023-06-30 19:53 UTC, timblaktu commented on README.md
> +When tagging a commit for a new release, the tag should follow the following format. Note that we use a monotonically-increasing one-based suffix to indicate the release number for the aforementioned
@laurenmengert I'm going to raise a new PR to address your feeddback since this one was abandoned.

2023-06-30 22:38 UTC, timblaktu commented on README.md
> +1. Create a new branch, named to clearly reflect the issue it corresponds to.
This has been done over in a follow-up PR for #25

2023-06-30 22:49 UTC, timblaktu commented on README.md
> +    * This is trivial using the [Development side bar on the issue page](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue).
I reworded this in the follow-up PR for #25:

Best practice is to click _Create a branch_ link in the [issue's development side bar](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue), and use the suggested branch name.

2023-06-30 22:51 UTC, timblaktu commented on README.md
> +When tagging a commit for a new release, the tag should follow the following format. Note that we use a monotonically-increasing one-based suffix to indicate the release number for the aforementioned
@laurenmengert @Vandiver247 I'm going to have to leave this request unanswered for now, since it seems the release process is not well defined. This will be discussed as a group and the contrib-guide updated accordingly, at a later time..

2023-06-30 23:17 UTC, timblaktu commented on README.md
> +    * `REF_NAME` variable matches the name of issue branch created earlier.
@laurenmengert I Changed this in the other PR to:

```
1. Update variables in the GitHub workflow yaml file corresponding to this repo (e.g. `suricata.yaml`) on your new branch in [dco-core's .github/workflows folder](https://github.com/naps-dev/dco-core/tree/main/.github/workflows) so:
    * `REF_NAME: <issue-specific branch created in this repo>`
    * `REF_TYPE: "branch"`
```

2023-07-10 21:07 UTC, closed without merging