Added suricata rule-sync side car container that does the following:
naps-dev/suricata pull request #34
Opened 2023-09-05 21:58 UTC by supcom234

1. Synchronizes the local.rules with main branch of custom gitrepo object
2. Updates and refreshes the rules using suricata-update command line.
3. Added CTI Offline rules so suricata-update will work in offline
4. Synchronizes global.rules with main branch of custom gitrepo object environment

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

For example:

Currently, the software does X, but this PR will allow it to do Y.

Currently, the software does not do X, but this PR will allow it to do X.

Currently, the software does X when specific thing happens causing bad things to happens, but this PR will fix it to do Y without the bad things.

New dependencies added:
- dependency 1 for reason
- dependency 2 for reason

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration - Change as necessary**:
* Kubernetes version:
* Hardware:
* Capability:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added a plain language explanation of the changes to the Unreleased section of the CHANGELOG.md file

2023-09-06 14:44 UTC, ericnnn123 reviewed
Looks pretty good

2023-09-06 14:44 UTC, ericnnn123 commented on chart/templates/daemonset.yaml
> +      - name: rule-sync
now that the suricata pod and rule-sync pod are merged I'd probably make this more descriptive `suricata-with-rules-sync` or something similar

2023-09-06 14:44 UTC, ericnnn123 commented on images/suricata/Dockerfile
> +RUN PACKAGES=( \
Merge this with the lines above

2023-09-06 14:44 UTC, ericnnn123 commented on images/suricata/gitea_bootstrap.py
> +        print("Successfully executed gitea bootstrap script!")
Add `self._session.close()` after the print statement.

2023-09-06 14:44 UTC, ericnnn123 commented on images/suricata/sync_rules.py
> +def run_shell_command(command: str) -> Tuple[str, int]:
Is this needed? It's not called anywhere.

Also if we're running commands it might be better to run them without shell

2023-09-06 14:44 UTC, ericnnn123 commented on images/suricata/sync_rules.py
> +        return ret_code
remove this line and assignment above(pylint standard)

2023-09-06 18:24 UTC, bburky requested changes
I'll review some more later, but here's some initial comments.

2023-09-06 18:24 UTC, bburky commented on images/suricata/gitea_bootstrap.py
> +        repo = self.create_repo(DEFAULT_REPO_NAME)
If this Job ever re-runs will it detect that the repo already exists and stop early?

I think this at least won't clobber people's repos? but will likely throw an error on this line the repo already exists.

2023-09-06 18:44 UTC, bburky requested changes

2023-09-06 18:44 UTC, bburky commented on images/suricata/Dockerfile
> +        "https://ti.stamus-networks.io/open/stamus-lateral-rules.tar.gz" \
This is fine for now, but I don't think a workflow where image rebuilds are required to update CTI. Ideally the image only needs updates when the source code updates.

One idea of an alternative is moving suricata-update into a cron-job-style CI job. We could have a cloud hosted `suricata-rules-updates` repo that runs this periodically and gets synced into the kit. Zarf could perhaps be used to package this. A small CTI-only Zarf package would be usable to get updates into an offline kit.

That's just an idea, but please make a ticket to track long term how we do frequent updates of CTI and sync them into the kit.

2023-09-08 20:46 UTC, supcom234 commented on chart/templates/daemonset.yaml
> +      - name: rule-sync
Fixed

2023-09-08 20:46 UTC, supcom234 commented on images/suricata/Dockerfile
> +RUN PACKAGES=( \
Fixed

2023-09-08 20:47 UTC, supcom234 commented on images/suricata/gitea_bootstrap.py
> +        print("Successfully executed gitea bootstrap script!")
fixed

2023-09-08 20:48 UTC, supcom234 commented on images/suricata/sync_rules.py
> +def run_shell_command(command: str) -> Tuple[str, int]:
Removed.  it was stale code that was not deleted.

2023-09-08 20:50 UTC, supcom234 commented on images/suricata/sync_rules.py
> +        return ret_code
Updated

2023-09-08 20:52 UTC, supcom234 commented on images/suricata/gitea_bootstrap.py
> +            print("Token didn't generate.")
Fixed

2023-09-08 21:39 UTC, supcom234 commented on images/suricata/gitea_bootstrap.py
> +        repo = self.create_repo(DEFAULT_REPO_NAME)
If the job reruns it will immediately because the token will already exist.  However even after I deleted the setup token via the frontend and re-ran the script I verified that the create_repo function will not clobber the repo.

2023-09-11 04:00 UTC, supcom234 commented on images/suricata/index.yaml
> +    url: http://gitea-http.dataplane-gitea.svc.cluster.local:3000/dataplane-git-user/suricata-rules-updates/raw/branch/main/emerging.rules.tar.gz
Updated code base to monitor suricata-rules-updates repo

2023-09-11 05:04 UTC, supcom234 commented on images/suricata/select_rules_repository.py
> +        if branches.ok:
It is an error if branches not ok.  However in this case the logic returns an empty list.  In which case the an error print string will subsequently be printed.

2023-09-11 05:09 UTC, supcom234 commented on images/suricata/Dockerfile
> +        "https://ti.stamus-networks.io/open/stamus-lateral-rules.tar.gz" \
Added Jira ticket to address this issue.

2023-09-11 15:12 UTC, docandrew commented on chart/templates/secret.yaml
This probably needs to be a templated var that we can update via Helm values or if the secret already exists for gitea admin then we can do a lookup for it.

2023-09-11 15:26 UTC, bburky approved these changes
Thanks for creating a ticket to address getting CTI updates without rebuilding the container is good. Changes look good, I'm fine with this as a first draft to merge something now.

2023-09-11 15:31 UTC, bburky commented on chart/templates/secret.yaml
Please make a ticket or note to do this later if this isn't done before merging

2023-09-11 16:10 UTC, merged